rgb_intrinsics:
   rows: 3
   cols: 3
   dt: d
   data: [1377.903797992831, 0.000000000000, 939.265767435483, 0.000000000000, 1378.596853789097, 543.722840196365, 0.000000000000, 0.000000000000, 1.000000000000]
rgb_distortion_coeffs:
   rows: 1
   cols: 5
   dt: d
   data: [0.141655009897, -0.427922046792, 0.000859113994, 0.001865152870, 0.372289863803]
hand_eye_transform:
   rows: 4
   cols: 4
   dt: d
   data: [0.007106980588, 0.004498701270, 0.999964625631, 0.048100252399, 0.012505312069, -0.999912082493, 0.004409586731, -0.009169796358, 0.999896548647, 0.012473530854, -0.007162613423, -0.031918466454, 0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]
depth_intrinsics:
   rows: 3
   cols: 3
   dt: d
   data: [643.00703526, 0.000000, 640.05313873, 0.000000, 643.00703526, 394.59240723, 0.000000, 0.000000, 1.000000]
depth_distortion_coeffs:
   rows: 1
   cols: 5
   dt: d
   data: [0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000]
depth_extrinsics:
   rows: 4
   cols: 4
   dt: d
   data: [0.999987971999, -0.002920499407, 0.003940373090, 0.015102103489, 0.002909143123, 0.999991607682, 0.002884692807, -0.000070988774, -0.003948764764, -0.002873195001, 0.999988075933, 0.000004818064, 0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]
ir1_intrinsics:
   rows: 3
   cols: 3
   dt: d
   data: [642.407016353611, 0.000000000000, 634.806361443121, 0.000000000000, 642.175968098198, 399.813851272794, 0.000000000000, 0.000000000000, 1.000000000000]
ir1_distortion_coeffs:
   rows: 1
   cols: 5
   dt: d
   data: [-0.057657753341, 0.080952720340, -0.000807697016, -0.000374940312, -0.041956643906]
ir2_intrinsics:
   rows: 3
   cols: 3
   dt: d
   data: [644.187548402914, 0.000000000000, 642.678242025660, 0.000000000000, 643.838102419627, 392.047659439874, 0.000000000000, 0.000000000000, 1.000000000000]
ir2_distortion_coeffs:
   rows: 1
   cols: 5
   dt: d
   data: [-0.056866591658, 0.073480549620, -0.000373768765, -0.000319176218, -0.030331996937]
ir_extrinsics:
   rows: 4
   cols: 4
   dt: d
   data: [0.999993933945, -0.001840198295, 0.002957320225, 0.049984515341, 0.001852563693, 0.999989531024, -0.004183999228, 0.000015114113, -0.002949589876, 0.004189452472, 0.999986874118, -0.000198498194, 0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]
rgb_width: 1920
rgb_height: 1080
depth_width: 1280
depth_height: 800
sensor_name: "realsense_d435"
serial_number: "n/a"
robot_name: "ur10"
z_scaling: 1.000000
depth_scale_mm: 0.100000
